
format = """
╭─$username$hostname$directory$conda${env_var.CONTAINER_ID}$git_branch$git_state$git_status$git_commit$git_metrics$java
╰─$character"""


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[❯](bold red) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = 'green bold'
style_root = 'red bold'
show_always = true
format = '[$user]($style)@'

[hostname]
ssh_only = false
format = '[$hostname]($style) '

[sudo]
disabled=false

[env_var.CONTAINER_ID]
default = ""
#variable = "CONTAINER_ID"
#symbol = "in 󰌽 "
style = "cyan bold"
format = "[$env_value]($style)"
